[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=0.2.0",
    "pandas>=2.3.2",
    "streamlit>=1.48.1",
    "pydantic>=2.0.0",
]
